
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action FileAction;

	private global::Gtk.Action FileAction1;

	private global::Gtk.Action quitAction;

	private global::Gtk.Action HelpAction;

	private global::Gtk.Action HelpAction1;

	private global::Gtk.Action executeAction;

	private global::Gtk.Action Action;

	private global::Gtk.Action aboutAction;

	private global::Gtk.Action zoomFitAction;

	private global::Gtk.Action Action1;

	private global::Gtk.Action openAction;

	private global::Gtk.Action saveAction;

	private global::Gtk.Action executeAction1;

	private global::Gtk.Action dialogErrorAction;

	private global::Gtk.ToggleAction editAction;

	private global::Gtk.Action sortAscendingAction;

	private global::Gtk.VBox mainVbox;

	private global::Gtk.MenuBar mainMenubar;

	private global::Gtk.Toolbar mainToolbar;

	private global::Gtk.HBox contentHbox;

	private global::Gtk.HPaned hpaned1;

	private global::Gtk.Notebook mainNotebook;

	private global::Gtk.ScrolledWindow designScrolledWindow;

	private global::Gtk.DrawingArea drawingarea;

	private global::Gtk.Label designTitleLabel;

	private global::Gtk.VBox previewVbox;

	private global::Gtk.ScrolledWindow previewScrolledWindow;

	private global::Gtk.DrawingArea previewDrawingArea;

	private global::Gtk.Toolbar previewToolbar;

	private global::Gtk.Label previewTitleLabel;

	private global::Gtk.VBox vbox2;

	private global::MonoDevelop.Components.PropertyGrid.PropertyGrid propertygrid2;

	private global::Gtk.Statusbar bottomStatusbar;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction, null);
		this.FileAction1 = new global::Gtk.Action ("FileAction1", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction1, null);
		this.quitAction = new global::Gtk.Action ("quitAction", global::Mono.Unix.Catalog.GetString ("Quit"), null, "gtk-quit");
		this.quitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Quit");
		w1.Add (this.quitAction, null);
		this.HelpAction = new global::Gtk.Action ("HelpAction", global::Mono.Unix.Catalog.GetString ("Help"), null, null);
		this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Help");
		w1.Add (this.HelpAction, null);
		this.HelpAction1 = new global::Gtk.Action ("HelpAction1", global::Mono.Unix.Catalog.GetString ("Help"), null, null);
		this.HelpAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("About");
		w1.Add (this.HelpAction1, null);
		this.executeAction = new global::Gtk.Action ("executeAction", null, null, "gtk-execute");
		w1.Add (this.executeAction, null);
		this.Action = new global::Gtk.Action ("Action", null, null, null);
		w1.Add (this.Action, null);
		this.aboutAction = new global::Gtk.Action ("aboutAction", global::Mono.Unix.Catalog.GetString ("About"), null, "gtk-about");
		this.aboutAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("About");
		w1.Add (this.aboutAction, null);
		this.zoomFitAction = new global::Gtk.Action ("zoomFitAction", null, null, "gtk-zoom-fit");
		w1.Add (this.zoomFitAction, null);
		this.Action1 = new global::Gtk.Action ("Action1", null, null, null);
		w1.Add (this.Action1, null);
		this.openAction = new global::Gtk.Action ("openAction", global::Mono.Unix.Catalog.GetString ("_Otwórz"), null, "gtk-open");
		this.openAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Otwórz");
		w1.Add (this.openAction, null);
		this.saveAction = new global::Gtk.Action ("saveAction", global::Mono.Unix.Catalog.GetString ("_Zapisz"), null, "gtk-save");
		this.saveAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Zapisz");
		w1.Add (this.saveAction, null);
		this.executeAction1 = new global::Gtk.Action ("executeAction1", null, null, "gtk-execute");
		w1.Add (this.executeAction1, null);
		this.dialogErrorAction = new global::Gtk.Action ("dialogErrorAction", null, null, "gtk-dialog-error");
		w1.Add (this.dialogErrorAction, null);
		this.editAction = new global::Gtk.ToggleAction ("editAction", null, null, "gtk-edit");
		w1.Add (this.editAction, null);
		this.sortAscendingAction = new global::Gtk.Action ("sortAscendingAction", null, null, "gtk-sort-ascending");
		w1.Add (this.sortAscendingAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MonoReports");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.AllowShrink = true;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.mainVbox = new global::Gtk.VBox ();
		this.mainVbox.Name = "mainVbox";
		this.mainVbox.Spacing = -1;
		// Container child mainVbox.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='mainMenubar'><menu name='FileAction1' action='FileAction1'><menuitem name='openAction' action='openAction'/><menuitem name='saveAction' action='saveAction'/><menuitem name='quitAction' action='quitAction'/></menu><menu name='HelpAction1' action='HelpAction1'><menuitem name='aboutAction' action='aboutAction'/></menu></menubar></ui>");
		this.mainMenubar = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/mainMenubar")));
		this.mainMenubar.Name = "mainMenubar";
		this.mainVbox.Add (this.mainMenubar);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.mainVbox[this.mainMenubar]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child mainVbox.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><toolbar name='mainToolbar'><toolitem name='editAction' action='editAction'/><toolitem name='sortAscendingAction' action='sortAscendingAction'/></toolbar></ui>");
		this.mainToolbar = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/mainToolbar")));
		this.mainToolbar.Name = "mainToolbar";
		this.mainToolbar.ShowArrow = false;
		this.mainToolbar.IconSize = ((global::Gtk.IconSize)(1));
		this.mainVbox.Add (this.mainToolbar);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.mainVbox[this.mainToolbar]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		// Container child mainVbox.Gtk.Box+BoxChild
		this.contentHbox = new global::Gtk.HBox ();
		this.contentHbox.Name = "contentHbox";
		this.contentHbox.Spacing = 6;
		// Container child contentHbox.Gtk.Box+BoxChild
		this.hpaned1 = new global::Gtk.HPaned ();
		this.hpaned1.CanFocus = true;
		this.hpaned1.Name = "hpaned1";
		this.hpaned1.Position = 576;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.mainNotebook = new global::Gtk.Notebook ();
		this.mainNotebook.CanFocus = true;
		this.mainNotebook.Events = ((global::Gdk.EventMask)(52992));
		this.mainNotebook.Name = "mainNotebook";
		this.mainNotebook.CurrentPage = 0;
		// Container child mainNotebook.Gtk.Notebook+NotebookChild
		this.designScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.designScrolledWindow.CanFocus = true;
		this.designScrolledWindow.Name = "designScrolledWindow";
		this.designScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child designScrolledWindow.Gtk.Container+ContainerChild
		global::Gtk.Viewport w4 = new global::Gtk.Viewport ();
		w4.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child GtkViewport.Gtk.Container+ContainerChild
		this.drawingarea = new global::Gtk.DrawingArea ();
		this.drawingarea.Events = ((global::Gdk.EventMask)(774));
		this.drawingarea.Name = "drawingarea";
		w4.Add (this.drawingarea);
		this.designScrolledWindow.Add (w4);
		this.mainNotebook.Add (this.designScrolledWindow);
		// Notebook tab
		this.designTitleLabel = new global::Gtk.Label ();
		this.designTitleLabel.Name = "designTitleLabel";
		this.designTitleLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("desing");
		this.mainNotebook.SetTabLabel (this.designScrolledWindow, this.designTitleLabel);
		this.designTitleLabel.ShowAll ();
		// Container child mainNotebook.Gtk.Notebook+NotebookChild
		this.previewVbox = new global::Gtk.VBox ();
		this.previewVbox.Name = "previewVbox";
		this.previewVbox.Spacing = 6;
		// Container child previewVbox.Gtk.Box+BoxChild
		this.previewScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.previewScrolledWindow.CanFocus = true;
		this.previewScrolledWindow.Name = "previewScrolledWindow";
		this.previewScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child previewScrolledWindow.Gtk.Container+ContainerChild
		global::Gtk.Viewport w8 = new global::Gtk.Viewport ();
		w8.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child GtkViewport1.Gtk.Container+ContainerChild
		this.previewDrawingArea = new global::Gtk.DrawingArea ();
		this.previewDrawingArea.Events = ((global::Gdk.EventMask)(774));
		this.previewDrawingArea.Name = "previewDrawingArea";
		w8.Add (this.previewDrawingArea);
		this.previewScrolledWindow.Add (w8);
		this.previewVbox.Add (this.previewScrolledWindow);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.previewVbox[this.previewScrolledWindow]));
		w11.Position = 0;
		// Container child previewVbox.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><toolbar name='previewToolbar'/></ui>");
		this.previewToolbar = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/previewToolbar")));
		this.previewToolbar.Name = "previewToolbar";
		this.previewToolbar.ShowArrow = false;
		this.previewVbox.Add (this.previewToolbar);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.previewVbox[this.previewToolbar]));
		w12.Position = 1;
		w12.Expand = false;
		w12.Fill = false;
		this.mainNotebook.Add (this.previewVbox);
		global::Gtk.Notebook.NotebookChild w13 = ((global::Gtk.Notebook.NotebookChild)(this.mainNotebook[this.previewVbox]));
		w13.Position = 1;
		// Notebook tab
		this.previewTitleLabel = new global::Gtk.Label ();
		this.previewTitleLabel.Name = "previewTitleLabel";
		this.previewTitleLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("preview");
		this.mainNotebook.SetTabLabel (this.previewVbox, this.previewTitleLabel);
		this.previewTitleLabel.ShowAll ();
		this.hpaned1.Add (this.mainNotebook);
		global::Gtk.Paned.PanedChild w14 = ((global::Gtk.Paned.PanedChild)(this.hpaned1[this.mainNotebook]));
		w14.Resize = false;
		w14.Shrink = false;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 3;
		// Container child vbox2.Gtk.Box+BoxChild
		this.propertygrid2 = new global::MonoDevelop.Components.PropertyGrid.PropertyGrid ();
		this.propertygrid2.CanDefault = true;
		this.propertygrid2.CanFocus = true;
		this.propertygrid2.Name = "propertygrid2";
		this.propertygrid2.ShowToolbar = false;
		this.propertygrid2.ShowHelp = false;
		this.vbox2.Add (this.propertygrid2);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.propertygrid2]));
		w15.Position = 0;
		this.hpaned1.Add (this.vbox2);
		global::Gtk.Paned.PanedChild w16 = ((global::Gtk.Paned.PanedChild)(this.hpaned1[this.vbox2]));
		w16.Resize = false;
		this.contentHbox.Add (this.hpaned1);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.contentHbox[this.hpaned1]));
		w17.PackType = ((global::Gtk.PackType)(1));
		w17.Position = 0;
		this.mainVbox.Add (this.contentHbox);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.mainVbox[this.contentHbox]));
		w18.Position = 2;
		// Container child mainVbox.Gtk.Box+BoxChild
		this.bottomStatusbar = new global::Gtk.Statusbar ();
		this.bottomStatusbar.Name = "bottomStatusbar";
		this.bottomStatusbar.Spacing = 6;
		this.mainVbox.Add (this.bottomStatusbar);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.mainVbox[this.bottomStatusbar]));
		w19.Position = 3;
		w19.Expand = false;
		w19.Fill = false;
		this.Add (this.mainVbox);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 835;
		this.DefaultHeight = 586;
		this.propertygrid2.HasDefault = true;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.quitAction.Activated += new global::System.EventHandler (this.OnQuitActionActivated);
		this.openAction.Activated += new global::System.EventHandler (this.OnOpenActionActivated);
		this.saveAction.Activated += new global::System.EventHandler (this.OnSaveActionActivated);
		this.editAction.Activated += new global::System.EventHandler (this.OnEditActionActivated);
		this.sortAscendingAction.Activated += new global::System.EventHandler (this.OnSortAscendingActionActivated);
		this.mainNotebook.SwitchPage += new global::Gtk.SwitchPageHandler (this.OnMainNotebookSwitchPage);
		this.drawingarea.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler (this.OnDrawingareaButtonPressEvent);
		this.drawingarea.ButtonReleaseEvent += new global::Gtk.ButtonReleaseEventHandler (this.OnDrawingareaButtonReleaseEvent);
		this.drawingarea.MotionNotifyEvent += new global::Gtk.MotionNotifyEventHandler (this.OnDrawingareaMotionNotifyEvent);
		this.drawingarea.ExposeEvent += new global::Gtk.ExposeEventHandler (this.OnDrawingareaExposeEvent);
		this.previewDrawingArea.ExposeEvent += new global::Gtk.ExposeEventHandler (this.OnPreviewDrawingareaExposeEvent);
		this.previewDrawingArea.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler (this.OnDrawingareaButtonPressEvent);
		this.previewDrawingArea.ButtonReleaseEvent += new global::Gtk.ButtonReleaseEventHandler (this.OnDrawingareaButtonReleaseEvent);
		this.previewDrawingArea.MotionNotifyEvent += new global::Gtk.MotionNotifyEventHandler (this.OnDrawingareaMotionNotifyEvent);
	}
}
