
// This file has been generated by the GUI designer. Do not modify.
namespace MonoReports.Gui
{
	public partial class ReportExplorer
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView exporerTreeview;

		private global::Gtk.Button updateFieldsFromDataSourceButton;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MonoReports.Gui.ReportExplorer
			global::Stetic.BinContainer.Attach (this);
			this.Name = "MonoReports.Gui.ReportExplorer";
			// Container child MonoReports.Gui.ReportExplorer.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.exporerTreeview = new global::Gtk.TreeView ();
			this.exporerTreeview.CanFocus = true;
			this.exporerTreeview.Name = "exporerTreeview";
			this.GtkScrolledWindow.Add (this.exporerTreeview);
			this.vbox1.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.GtkScrolledWindow]));
			w2.Position = 1;
			// Container child vbox1.Gtk.Box+BoxChild
			this.updateFieldsFromDataSourceButton = new global::Gtk.Button ();
			this.updateFieldsFromDataSourceButton.CanFocus = true;
			this.updateFieldsFromDataSourceButton.Name = "updateFieldsFromDataSourceButton";
			this.updateFieldsFromDataSourceButton.UseUnderline = true;
			this.updateFieldsFromDataSourceButton.Label = global::Mono.Unix.Catalog.GetString ("Update from DataSource");
			this.vbox1.Add (this.updateFieldsFromDataSourceButton);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.updateFieldsFromDataSourceButton]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.updateFieldsFromDataSourceButton.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler (this.OnUpdateFieldsFromDataSourceButtonButtonPressEvent);
			this.updateFieldsFromDataSourceButton.Clicked += new global::System.EventHandler (this.OnUpdateFieldsFromDataSourceButtonClicked);
		}
	}
}
