
// This file has been generated by the GUI designer. Do not modify.
namespace MonoReports.Gui
{
	public partial class ReportExplorer
	{
		private global::Gtk.VPaned vpaned1;
		private global::Gtk.VPaned vpaned2;
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		private global::Gtk.TextView scriptTextView;
		private global::Gtk.VBox vbox1;
		private global::Gtk.ScrolledWindow GtkScrolledWindow2;
		private global::Gtk.TextView outputTextview;
		private global::Gtk.Button execScriptButton;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TreeView exporerTreeview;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MonoReports.Gui.ReportExplorer
			global::Stetic.BinContainer.Attach (this);
			this.Name = "MonoReports.Gui.ReportExplorer";
			// Container child MonoReports.Gui.ReportExplorer.Gtk.Container+ContainerChild
			this.vpaned1 = new global::Gtk.VPaned ();
			this.vpaned1.CanFocus = true;
			this.vpaned1.Name = "vpaned1";
			this.vpaned1.Position = 280;
			// Container child vpaned1.Gtk.Paned+PanedChild
			this.vpaned2 = new global::Gtk.VPaned ();
			this.vpaned2.CanFocus = true;
			this.vpaned2.Name = "vpaned2";
			this.vpaned2.Position = 182;
			// Container child vpaned2.Gtk.Paned+PanedChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.scriptTextView = new global::Gtk.TextView ();
			this.scriptTextView.CanFocus = true;
			this.scriptTextView.Name = "scriptTextView";
			this.GtkScrolledWindow1.Add (this.scriptTextView);
			this.vpaned2.Add (this.GtkScrolledWindow1);
			global::Gtk.Paned.PanedChild w2 = ((global::Gtk.Paned.PanedChild)(this.vpaned2 [this.GtkScrolledWindow1]));
			w2.Resize = false;
			// Container child vpaned2.Gtk.Paned+PanedChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
			this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
			this.outputTextview = new global::Gtk.TextView ();
			this.outputTextview.CanFocus = true;
			this.outputTextview.Name = "outputTextview";
			this.GtkScrolledWindow2.Add (this.outputTextview);
			this.vbox1.Add (this.GtkScrolledWindow2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow2]));
			w4.Position = 0;
			// Container child vbox1.Gtk.Box+BoxChild
			this.execScriptButton = new global::Gtk.Button ();
			this.execScriptButton.CanFocus = true;
			this.execScriptButton.Name = "execScriptButton";
			this.execScriptButton.UseUnderline = true;
			this.execScriptButton.Label = global::Mono.Unix.Catalog.GetString ("Execute");
			this.vbox1.Add (this.execScriptButton);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.execScriptButton]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			this.vpaned2.Add (this.vbox1);
			this.vpaned1.Add (this.vpaned2);
			global::Gtk.Paned.PanedChild w7 = ((global::Gtk.Paned.PanedChild)(this.vpaned1 [this.vpaned2]));
			w7.Resize = false;
			// Container child vpaned1.Gtk.Paned+PanedChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.exporerTreeview = new global::Gtk.TreeView ();
			this.exporerTreeview.CanFocus = true;
			this.exporerTreeview.Name = "exporerTreeview";
			this.GtkScrolledWindow.Add (this.exporerTreeview);
			this.vpaned1.Add (this.GtkScrolledWindow);
			this.Add (this.vpaned1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.execScriptButton.Clicked += new global::System.EventHandler (this.OnExecScriptButtonClicked);
		}
	}
}
