
// This file has been generated by the GUI designer. Do not modify.
namespace MonoReports.Gui.Widgets
{
	public partial class ReportExplorer
	{
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TreeView exporerTreeview;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MonoReports.Gui.Widgets.ReportExplorer
			global::Stetic.BinContainer.Attach (this);
			this.Name = "MonoReports.Gui.Widgets.ReportExplorer";
			// Container child MonoReports.Gui.Widgets.ReportExplorer.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.exporerTreeview = new global::Gtk.TreeView ();
			this.exporerTreeview.CanFocus = true;
			this.exporerTreeview.Events = ((global::Gdk.EventMask)(4194302));
			this.exporerTreeview.ExtensionEvents = ((global::Gdk.ExtensionMode)(1));
			this.exporerTreeview.Name = "exporerTreeview";
			this.GtkScrolledWindow.Add (this.exporerTreeview);
			this.Add (this.GtkScrolledWindow);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.exporerTreeview.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler (this.OnExporerTreeviewButtonPressEvent);
		}
	}
}
