
// This file has been generated by the GUI designer. Do not modify.
namespace MonoReports.Gui.Widgets
{
	public partial class MainDesignView
	{
		private global::Gtk.UIManager UIManager;
		private global::Gtk.Notebook mainNotebook;
		private global::Gtk.ScrolledWindow designScrolledWindow;
		private global::Gtk.DrawingArea drawingarea;
		private global::Gtk.Label designTitleLabel;
		private global::Gtk.VBox previewVbox;
		private global::Gtk.ScrolledWindow previewScrolledWindow;
		private global::Gtk.DrawingArea previewDrawingArea;
		private global::Gtk.Toolbar previewToolbar;
		private global::Gtk.Label previewTitleLabel;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MonoReports.Gui.Widgets.MainDesignView
			Stetic.BinContainer w1 = global::Stetic.BinContainer.Attach (this);
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w2 = new global::Gtk.ActionGroup ("Default");
			this.UIManager.InsertActionGroup (w2, 0);
			this.Name = "MonoReports.Gui.Widgets.MainDesignView";
			// Container child MonoReports.Gui.Widgets.MainDesignView.Gtk.Container+ContainerChild
			this.mainNotebook = new global::Gtk.Notebook ();
			this.mainNotebook.CanFocus = true;
			this.mainNotebook.Events = ((global::Gdk.EventMask)(52992));
			this.mainNotebook.Name = "mainNotebook";
			this.mainNotebook.CurrentPage = 0;
			// Container child mainNotebook.Gtk.Notebook+NotebookChild
			this.designScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.designScrolledWindow.CanFocus = true;
			this.designScrolledWindow.Name = "designScrolledWindow";
			this.designScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child designScrolledWindow.Gtk.Container+ContainerChild
			global::Gtk.Viewport w3 = new global::Gtk.Viewport ();
			w3.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.drawingarea = new global::Gtk.DrawingArea ();
			this.drawingarea.CanFocus = true;
			this.drawingarea.Events = ((global::Gdk.EventMask)(69382));
			this.drawingarea.ExtensionEvents = ((global::Gdk.ExtensionMode)(1));
			this.drawingarea.Name = "drawingarea";
			w3.Add (this.drawingarea);
			this.designScrolledWindow.Add (w3);
			this.mainNotebook.Add (this.designScrolledWindow);
			// Notebook tab
			this.designTitleLabel = new global::Gtk.Label ();
			this.designTitleLabel.Name = "designTitleLabel";
			this.designTitleLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("desing");
			this.mainNotebook.SetTabLabel (this.designScrolledWindow, this.designTitleLabel);
			this.designTitleLabel.ShowAll ();
			// Container child mainNotebook.Gtk.Notebook+NotebookChild
			this.previewVbox = new global::Gtk.VBox ();
			this.previewVbox.Name = "previewVbox";
			this.previewVbox.Spacing = 6;
			// Container child previewVbox.Gtk.Box+BoxChild
			this.previewScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.previewScrolledWindow.CanFocus = true;
			this.previewScrolledWindow.Name = "previewScrolledWindow";
			this.previewScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child previewScrolledWindow.Gtk.Container+ContainerChild
			global::Gtk.Viewport w7 = new global::Gtk.Viewport ();
			w7.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport1.Gtk.Container+ContainerChild
			this.previewDrawingArea = new global::Gtk.DrawingArea ();
			this.previewDrawingArea.Events = ((global::Gdk.EventMask)(774));
			this.previewDrawingArea.Name = "previewDrawingArea";
			w7.Add (this.previewDrawingArea);
			this.previewScrolledWindow.Add (w7);
			this.previewVbox.Add (this.previewScrolledWindow);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.previewVbox [this.previewScrolledWindow]));
			w10.Position = 0;
			// Container child previewVbox.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><toolbar name='previewToolbar'/></ui>");
			this.previewToolbar = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/previewToolbar")));
			this.previewToolbar.Name = "previewToolbar";
			this.previewToolbar.ShowArrow = false;
			this.previewVbox.Add (this.previewToolbar);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.previewVbox [this.previewToolbar]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			this.mainNotebook.Add (this.previewVbox);
			global::Gtk.Notebook.NotebookChild w12 = ((global::Gtk.Notebook.NotebookChild)(this.mainNotebook [this.previewVbox]));
			w12.Position = 1;
			// Notebook tab
			this.previewTitleLabel = new global::Gtk.Label ();
			this.previewTitleLabel.Name = "previewTitleLabel";
			this.previewTitleLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("preview");
			this.mainNotebook.SetTabLabel (this.previewVbox, this.previewTitleLabel);
			this.previewTitleLabel.ShowAll ();
			this.Add (this.mainNotebook);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			w1.SetUiManager (UIManager);
			this.Hide ();
			this.mainNotebook.SwitchPage += new global::Gtk.SwitchPageHandler (this.OnMainNotebookSwitchPage);
			this.drawingarea.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler (this.OnDrawingareaButtonPressEvent);
			this.drawingarea.ButtonReleaseEvent += new global::Gtk.ButtonReleaseEventHandler (this.OnDrawingareaButtonReleaseEvent);
			this.drawingarea.MotionNotifyEvent += new global::Gtk.MotionNotifyEventHandler (this.OnDrawingareaMotionNotifyEvent);
			this.drawingarea.ExposeEvent += new global::Gtk.ExposeEventHandler (this.OnDrawingareaExposeEvent);
			this.drawingarea.KeyPressEvent += new global::Gtk.KeyPressEventHandler (this.OnDrawingareaKeyPressEvent);
			this.drawingarea.KeyReleaseEvent += new global::Gtk.KeyReleaseEventHandler (this.OnDrawingareaKeyReleaseEvent);
			this.previewDrawingArea.ExposeEvent += new global::Gtk.ExposeEventHandler (this.OnPreviewDrawingareaExposeEvent);
			this.previewDrawingArea.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler (this.OnDrawingareaButtonPressEvent);
			this.previewDrawingArea.ButtonReleaseEvent += new global::Gtk.ButtonReleaseEventHandler (this.OnDrawingareaButtonReleaseEvent);
			this.previewDrawingArea.MotionNotifyEvent += new global::Gtk.MotionNotifyEventHandler (this.OnDrawingareaMotionNotifyEvent);
		}
	}
}
